### ISSUE TITLE
6-well plate does it work

### ISSUE THREAD

**Issue by popcornm** [plaque2/matlab#4]
Hi.
I wonder this plaque2 software, can it perform a 6-well plate analysis?
Are there alternatives for 96-well plate?

**Comment by vandriasyan** [comment]
Hi,
It works pretty much with any single channel grayscale image, just your foreground has to be bright and the background dark.

**Comment by popcornm** [comment]
HiThank you for answer. so impressive. Best wishes. 12:57, 14 Ocak 2020, vandriasyan <notifications@github.com>:Hi,
It works pretty much with any single channel grayscale image, just your foreground has to be bright and the background dark.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Yandex.Mail mobil uygulamasından gönderildi

**Comment by popcornm** [comment]
Hi,I have one more question. Black 6-well imaging plate sales are not available on the market.A fluorescent intensity-based image obtained by any black-colored plastic-based 6-well or non-colored an ordinary plate by software can it work?Tkanks.14.01.2020, 12:57, "vandriasyan" <notifications@github.com>:Hi,
It works pretty much with any single channel grayscale image, just your foreground has to be bright and the background dark.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Banu COPUROGLUBIOHACKERGEEN Biotechnology, Inc.-- **********************************************************************Legal notice:This message and its contents including any attachments is highly confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please telephone or email the sender and delete this message and any attachment from your system; you must not copy or disclose the contents of this message or any attachment to any other person. Yasal Uyarı:Bu mesaj/konuşma ve her türlü ekleri dahil olmak üzere tüm içeriği çok gizlidir. Kişiye özel bilgiler içermekte veya yasal olarak imtiyazlı olabilir ve ifşaattan korunmalıdır. Eğer bu mesajın size gönderilmediğini yada yanlışlıkla gönderildiğini düşünüyorsanız; veya mesajın hedeflenen alıcısı siz değilseniz, lütfen gönderene telefonla veya email ile ulaşarak durumu bildiriniz. Bu mesajı, tüm bağlantılarını ve eklerini sisteminizden siliniz. Bu mesajı kopyalamamalı, mesajın içeriğini açığa vurmamalı ve bu mesajla ilgili bağlantıları başka insanlarla paylaşmamalısınız.  **********************************************************************
